"""Assemble data/catalog/sources/*.json into the unified ballot-measure
catalog (data/catalog/ballot_measures.csv) and the overlap-structure
design matrix (data/catalog/DESIGN_MATRIX.md).

This is step 1 of docs/MEASUREMENT_DESIGN.md: the catalog is statewide
METADATA (state, date, topic, direction, result, severity note, what
else shared the ballot), researched from Ballotpedia/NCSL. It contains
no county data; the design matrix it computes — same-ballot pairs,
cross-topic ballots, repeat geographies — is the county-ingest priority
list, because overlap structure (not volume) is what identifies measure
severity separately from electorate drift.

Thin data plumbing in the scripts/ orchestration tier (like
export_web_data.py): logic that grows here gets promoted to the tested
geofluid library per the contract.
"""

import csv
import json
import re
from collections import Counter, defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "data" / "catalog" / "sources"
OUT_CSV = ROOT / "data" / "catalog" / "ballot_measures.csv"
OUT_MD = ROOT / "data" / "catalog" / "DESIGN_MATRIX.md"
TOPICS = ["abortion", "marriage", "cannabis", "labor", "healthcare"]

COLUMNS = [
    "measure_id",
    "ballot_id",
    "state",
    "election_date",
    "election_type",
    "topic",
    "measure_name",
    "description_short",
    "progressive_side",
    "yes_pct",
    "outcome",
    "severity_note",
    "same_ballot_catalog_ids",
    "same_ballot_companions",
    "source_url",
]


def _slug(s: str) -> str:
    return re.sub(r"[^a-z0-9]+", "_", s.lower()).strip("_")


def load_measures() -> list[dict]:
    rows: list[dict] = []
    seen: set[tuple] = set()
    for topic in TOPICS:
        with open(SRC / f"{topic}.json", encoding="utf-8") as f:
            for m in json.load(f):
                key = (m["state"], m["election_date"], m["measure_name"])
                if key in seen:  # a measure researched by two corpora
                    continue
                seen.add(key)
                m["topic"] = topic
                date = (m["election_date"] or "nd")[:10].replace("-", "")
                m["measure_id"] = f"{m['state'].lower()}_{date}_{_slug(m['measure_name'])[:40]}"
                m["ballot_id"] = f"{m['state']}_{m['election_date']}"
                rows.append(m)
    return sorted(rows, key=lambda m: (m["election_date"] or "", m["state"]))


def main() -> None:
    rows = load_measures()

    ballots: dict[str, list[dict]] = defaultdict(list)
    for m in rows:
        ballots[m["ballot_id"]].append(m)

    # Same-ballot pairs among catalogued measures: the severity
    # identifiers (identical electorate, same day — differences are
    # measure properties). Cross-topic pairs additionally feed the
    # dimensionality test.
    pairs = {b: ms for b, ms in ballots.items() if len(ms) >= 2}
    cross = {b: ms for b, ms in pairs.items() if len({m["topic"] for m in ms}) >= 2}

    # Repeat geographies: same state + topic voting on 2+ dates — the
    # drift anchors (cutpoint approximately held, electorate moved).
    state_topic: dict[tuple, set] = defaultdict(set)
    for m in rows:
        state_topic[(m["state"], m["topic"])].add(m["election_date"])
    repeats = {k: sorted(v) for k, v in state_topic.items() if len(v) >= 2}

    with open(OUT_CSV, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=COLUMNS, extrasaction="ignore")
        writer.writeheader()
        for m in rows:
            m["same_ballot_catalog_ids"] = "; ".join(
                x["measure_id"]
                for x in ballots[m["ballot_id"]]
                if x["measure_id"] != m["measure_id"]
            )
            m["same_ballot_companions"] = "; ".join(m.get("same_ballot_companions") or [])
            writer.writerow(m)

    with open(OUT_MD, "w", encoding="utf-8") as f:
        f.write("# Catalog design matrix\n\n")
        f.write(
            "Auto-generated by `scripts/assemble_measure_catalog.py` from "
            "`data/catalog/sources/*.json`. See `docs/MEASUREMENT_DESIGN.md` "
            "for why each structure matters.\n\n"
        )
        f.write(f"- measures: **{len(rows)}**\n")
        f.write(f"- topics: {dict(Counter(m['topic'] for m in rows))}\n")
        f.write(f"- ballots with 2+ catalogued measures: **{len(pairs)}**\n")
        f.write(f"- of those, cross-topic ballots: **{len(cross)}**\n")
        f.write(f"- repeat state-topic geographies: **{len(repeats)}**\n\n")
        f.write("## Cross-topic same-ballot pairs (severity identifiers)\n\n")
        for b in sorted(cross):
            names = ", ".join(f"{m['measure_name']} [{m['topic']}]" for m in cross[b])
            f.write(f"- **{b}**: {names}\n")
        f.write("\n## Repeat geographies (drift anchors), 3+ dates\n\n")
        for (state, topic), dates in sorted(repeats.items()):
            if len(dates) >= 3:
                f.write(f"- **{state} / {topic}**: {', '.join(dates)}\n")

    print(f"catalog: {len(rows)} measures -> {OUT_CSV}")
    print(f"same-ballot: {len(pairs)} ballots ({len(cross)} cross-topic)")
    print(f"repeat geographies: {len(repeats)}")


if __name__ == "__main__":
    main()
